import { Product, Settings } from '../types';

export const defaultSettings: Settings = {
  shopName: 'گالری طلا و جواهر میلاد',
  shopPhone: '۰۲۱-۸۸۸۸۸۸۸۸',
  shopAddress: 'تهران، خیابان طلا، پلاک ۱۲',
  pricePerGram18: 3450000,
  profitPercent: 7,
  taxPercent: 9,
};

export const seedProducts: Product[] = [
  {
    id: 'p1',
    code: 'G-1001',
    name: 'انگشتر طلای زنانه',
    category: 'jewelry',
    karat: 18,
    weight: 4.25,
    wagePercent: 12,
    stock: 5,
    accent: '#e9b949',
  },
  {
    id: 'p2',
    code: 'G-1002',
    name: 'گردنبند طرح قلب',
    category: 'jewelry',
    karat: 18,
    weight: 6.8,
    wagePercent: 15,
    stock: 3,
    accent: '#f5d98b',
  },
  {
    id: 'p3',
    code: 'G-1003',
    name: 'دستبند النگویی',
    category: 'gold',
    karat: 18,
    weight: 12.5,
    wagePercent: 9,
    stock: 8,
    accent: '#d4af37',
  },
  {
    id: 'p4',
    code: 'C-2001',
    name: 'سکه تمام بهار آزادی',
    category: 'coin',
    karat: 21.6,
    weight: 8.133,
    wagePercent: 3,
    stock: 10,
    accent: '#c9a227',
  },
  {
    id: 'p5',
    code: 'C-2002',
    name: 'نیم سکه بهار آزادی',
    category: 'coin',
    karat: 21.6,
    weight: 4.066,
    wagePercent: 3,
    stock: 12,
    accent: '#b8860b',
  },
  {
    id: 'p6',
    code: 'G-1004',
    name: 'سرویس طلای عروس',
    category: 'jewelry',
    karat: 18,
    weight: 35.4,
    wagePercent: 18,
    stock: 2,
    accent: '#f0c75e',
  },
  {
    id: 'p7',
    code: 'G-1005',
    name: 'گوشواره حلقه‌ای',
    category: 'jewelry',
    karat: 18,
    weight: 2.15,
    wagePercent: 14,
    stock: 15,
    accent: '#e6be69',
  },
  {
    id: 'p8',
    code: 'G-1006',
    name: 'آویز گردنبند اسم',
    category: 'jewelry',
    karat: 18,
    weight: 1.9,
    wagePercent: 20,
    stock: 20,
    accent: '#eac96b',
  },
];
